DROP TABLE IF EXISTS daily_shop;

DROP TABLE IF EXISTS daily_task;

DROP TABLE IF EXISTS daily_sign;

DROP TABLE IF EXISTS chapter;

DROP TABLE IF EXISTS tower;

DROP TABLE IF EXISTS prop;

DROP TABLE IF EXISTS skin;

DROP TABLE IF EXISTS player;
