// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapter_queries.sql

package playersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChapterProgressByPlayerID = `-- name: GetChapterProgressByPlayerID :many
SELECT
    chapter_id,
    checked_checkpoints
FROM
    chapter
WHERE
    player_id = $1
`

type GetChapterProgressByPlayerIDRow struct {
	ChapterID          int32  `db:"chapter_id" json:"chapter_id"`
	CheckedCheckpoints []byte `db:"checked_checkpoints" json:"checked_checkpoints"`
}

func (q *Queries) GetChapterProgressByPlayerID(ctx context.Context, playerID pgtype.UUID) ([]GetChapterProgressByPlayerIDRow, error) {
	rows, err := q.db.Query(ctx, getChapterProgressByPlayerID, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChapterProgressByPlayerIDRow{}
	for rows.Next() {
		var i GetChapterProgressByPlayerIDRow
		if err := rows.Scan(&i.ChapterID, &i.CheckedCheckpoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChapterProgressByPlayerIDAndChapterID = `-- name: GetChapterProgressByPlayerIDAndChapterID :one
SELECT
    chapter_id,
    checked_checkpoints
FROM
    chapter
WHERE
    player_id = $1
`

type GetChapterProgressByPlayerIDAndChapterIDRow struct {
	ChapterID          int32  `db:"chapter_id" json:"chapter_id"`
	CheckedCheckpoints []byte `db:"checked_checkpoints" json:"checked_checkpoints"`
}

func (q *Queries) GetChapterProgressByPlayerIDAndChapterID(ctx context.Context, playerID pgtype.UUID) (GetChapterProgressByPlayerIDAndChapterIDRow, error) {
	row := q.db.QueryRow(ctx, getChapterProgressByPlayerIDAndChapterID, playerID)
	var i GetChapterProgressByPlayerIDAndChapterIDRow
	err := row.Scan(&i.ChapterID, &i.CheckedCheckpoints)
	return i, err
}

const upsertChapterProgressOnPlayer = `-- name: UpsertChapterProgressOnPlayer :one
INSERT INTO
    chapter (player_id, chapter_id, checked_checkpoints)
VALUES
    ($1, $2, $3)
ON CONFLICT (chapter_id, player_id) DO UPDATE
SET
    checked_checkpoints = EXCLUDED.checked_checkpoints,
    updated_at = NOW()
RETURNING
    chapter_id,
    checked_checkpoints
`

type UpsertChapterProgressOnPlayerParams struct {
	PlayerID           pgtype.UUID `db:"player_id" json:"player_id"`
	ChapterID          int32       `db:"chapter_id" json:"chapter_id"`
	CheckedCheckpoints []byte      `db:"checked_checkpoints" json:"checked_checkpoints"`
}

type UpsertChapterProgressOnPlayerRow struct {
	ChapterID          int32  `db:"chapter_id" json:"chapter_id"`
	CheckedCheckpoints []byte `db:"checked_checkpoints" json:"checked_checkpoints"`
}

func (q *Queries) UpsertChapterProgressOnPlayer(ctx context.Context, arg UpsertChapterProgressOnPlayerParams) (UpsertChapterProgressOnPlayerRow, error) {
	row := q.db.QueryRow(ctx, upsertChapterProgressOnPlayer, arg.PlayerID, arg.ChapterID, arg.CheckedCheckpoints)
	var i UpsertChapterProgressOnPlayerRow
	err := row.Scan(&i.ChapterID, &i.CheckedCheckpoints)
	return i, err
}
