// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_task_queries.sql

package playersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDailyTask = `-- name: ClaimDailyTask :one
UPDATE daily_task
SET
    claimed = TRUE,
    points_earned = $4,
    updated_at = NOW()
WHERE player_id = $1
    AND task_id = $2
    AND day_start_at = $3
RETURNING task_id,
          progress,
          claimed,
          points_earned
`

type ClaimDailyTaskParams struct {
	PlayerID     pgtype.UUID        `db:"player_id" json:"player_id"`
	TaskID       int32              `db:"task_id" json:"task_id"`
	DayStartAt   pgtype.Timestamptz `db:"day_start_at" json:"day_start_at"`
	PointsEarned int32              `db:"points_earned" json:"points_earned"`
}

type ClaimDailyTaskRow struct {
	TaskID       int32 `db:"task_id" json:"task_id"`
	Progress     int32 `db:"progress" json:"progress"`
	Claimed      bool  `db:"claimed" json:"claimed"`
	PointsEarned int32 `db:"points_earned" json:"points_earned"`
}

func (q *Queries) ClaimDailyTask(ctx context.Context, arg ClaimDailyTaskParams) (ClaimDailyTaskRow, error) {
	row := q.db.QueryRow(ctx, claimDailyTask,
		arg.PlayerID,
		arg.TaskID,
		arg.DayStartAt,
		arg.PointsEarned,
	)
	var i ClaimDailyTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.Progress,
		&i.Claimed,
		&i.PointsEarned,
	)
	return i, err
}

const getDailyTasksByPlayerID = `-- name: GetDailyTasksByPlayerID :many
SELECT
    task_id,
    progress,
    claimed,
    points_earned
FROM daily_task
WHERE player_id = $1
    AND day_start_at = $2
`

type GetDailyTasksByPlayerIDParams struct {
	PlayerID   pgtype.UUID        `db:"player_id" json:"player_id"`
	DayStartAt pgtype.Timestamptz `db:"day_start_at" json:"day_start_at"`
}

type GetDailyTasksByPlayerIDRow struct {
	TaskID       int32 `db:"task_id" json:"task_id"`
	Progress     int32 `db:"progress" json:"progress"`
	Claimed      bool  `db:"claimed" json:"claimed"`
	PointsEarned int32 `db:"points_earned" json:"points_earned"`
}

func (q *Queries) GetDailyTasksByPlayerID(ctx context.Context, arg GetDailyTasksByPlayerIDParams) ([]GetDailyTasksByPlayerIDRow, error) {
	rows, err := q.db.Query(ctx, getDailyTasksByPlayerID, arg.PlayerID, arg.DayStartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyTasksByPlayerIDRow{}
	for rows.Next() {
		var i GetDailyTasksByPlayerIDRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Progress,
			&i.Claimed,
			&i.PointsEarned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProgressForDailyTask = `-- name: UpsertProgressForDailyTask :one
INSERT INTO daily_task (
    player_id,
    task_id,
    day_start_at,
    progress
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (player_id, task_id, day_start_at) DO UPDATE SET
    progress = EXCLUDED.progress,
    updated_at = NOW()
RETURNING task_id,
          progress,
          claimed,
          points_earned
`

type UpsertProgressForDailyTaskParams struct {
	PlayerID   pgtype.UUID        `db:"player_id" json:"player_id"`
	TaskID     int32              `db:"task_id" json:"task_id"`
	DayStartAt pgtype.Timestamptz `db:"day_start_at" json:"day_start_at"`
	Progress   int32              `db:"progress" json:"progress"`
}

type UpsertProgressForDailyTaskRow struct {
	TaskID       int32 `db:"task_id" json:"task_id"`
	Progress     int32 `db:"progress" json:"progress"`
	Claimed      bool  `db:"claimed" json:"claimed"`
	PointsEarned int32 `db:"points_earned" json:"points_earned"`
}

func (q *Queries) UpsertProgressForDailyTask(ctx context.Context, arg UpsertProgressForDailyTaskParams) (UpsertProgressForDailyTaskRow, error) {
	row := q.db.QueryRow(ctx, upsertProgressForDailyTask,
		arg.PlayerID,
		arg.TaskID,
		arg.DayStartAt,
		arg.Progress,
	)
	var i UpsertProgressForDailyTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.Progress,
		&i.Claimed,
		&i.PointsEarned,
	)
	return i, err
}
