// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_sign_in_queries.sql

package playersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySignInByPlayerID = `-- name: GetDailySignInByPlayerID :one
SELECT
    id,
    week_start_at,
    claimed_days
FROM
    daily_sign_in
WHERE
    player_id = $1
    AND week_start_at = $2
`

type GetDailySignInByPlayerIDParams struct {
	PlayerID    pgtype.UUID        `db:"player_id" json:"player_id"`
	WeekStartAt pgtype.Timestamptz `db:"week_start_at" json:"week_start_at"`
}

type GetDailySignInByPlayerIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WeekStartAt pgtype.Timestamptz `db:"week_start_at" json:"week_start_at"`
	ClaimedDays []byte             `db:"claimed_days" json:"claimed_days"`
}

func (q *Queries) GetDailySignInByPlayerID(ctx context.Context, arg GetDailySignInByPlayerIDParams) (GetDailySignInByPlayerIDRow, error) {
	row := q.db.QueryRow(ctx, getDailySignInByPlayerID, arg.PlayerID, arg.WeekStartAt)
	var i GetDailySignInByPlayerIDRow
	err := row.Scan(&i.ID, &i.WeekStartAt, &i.ClaimedDays)
	return i, err
}

const initDailySignIn = `-- name: InitDailySignIn :one
INSERT INTO
    daily_sign_in (player_id, week_start_at)
VALUES
    ($1, $2)
RETURNING
    id,
    week_start_at,
    claimed_days
`

type InitDailySignInParams struct {
	PlayerID    pgtype.UUID        `db:"player_id" json:"player_id"`
	WeekStartAt pgtype.Timestamptz `db:"week_start_at" json:"week_start_at"`
}

type InitDailySignInRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WeekStartAt pgtype.Timestamptz `db:"week_start_at" json:"week_start_at"`
	ClaimedDays []byte             `db:"claimed_days" json:"claimed_days"`
}

func (q *Queries) InitDailySignIn(ctx context.Context, arg InitDailySignInParams) (InitDailySignInRow, error) {
	row := q.db.QueryRow(ctx, initDailySignIn, arg.PlayerID, arg.WeekStartAt)
	var i InitDailySignInRow
	err := row.Scan(&i.ID, &i.WeekStartAt, &i.ClaimedDays)
	return i, err
}

const markDailySignInDays = `-- name: MarkDailySignInDays :one
UPDATE daily_sign_in
SET
    claimed_days = $3
WHERE
    player_id = $1
    AND id = $2
RETURNING
    id,
    week_start_at,
    claimed_days
`

type MarkDailySignInDaysParams struct {
	PlayerID    pgtype.UUID `db:"player_id" json:"player_id"`
	ID          pgtype.UUID `db:"id" json:"id"`
	ClaimedDays []byte      `db:"claimed_days" json:"claimed_days"`
}

type MarkDailySignInDaysRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WeekStartAt pgtype.Timestamptz `db:"week_start_at" json:"week_start_at"`
	ClaimedDays []byte             `db:"claimed_days" json:"claimed_days"`
}

func (q *Queries) MarkDailySignInDays(ctx context.Context, arg MarkDailySignInDaysParams) (MarkDailySignInDaysRow, error) {
	row := q.db.QueryRow(ctx, markDailySignInDays, arg.PlayerID, arg.ID, arg.ClaimedDays)
	var i MarkDailySignInDaysRow
	err := row.Scan(&i.ID, &i.WeekStartAt, &i.ClaimedDays)
	return i, err
}
