// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package playersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error)
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (GetPlayerByIDRow, error)
}

var _ Querier = (*Queries)(nil)
