// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package playersqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTowerTicketsToPlayer(ctx context.Context, arg AddTowerTicketsToPlayerParams) (AddTowerTicketsToPlayerRow, error)
	ClaimDailyTask(ctx context.Context, arg ClaimDailyTaskParams) (ClaimDailyTaskRow, error)
	CompleteBattleHistory(ctx context.Context, arg CompleteBattleHistoryParams) (BattleHistory, error)
	ConsumeTowerTicketsFromPlayer(ctx context.Context, arg ConsumeTowerTicketsFromPlayerParams) (ConsumeTowerTicketsFromPlayerRow, error)
	CreateNewPlayer(ctx context.Context, arg CreateNewPlayerParams) (CreateNewPlayerRow, error)
	GetBattleHistoryByID(ctx context.Context, id pgtype.UUID) (BattleHistory, error)
	GetChapterProgressByPlayerID(ctx context.Context, playerID pgtype.UUID) ([]GetChapterProgressByPlayerIDRow, error)
	GetChapterProgressByPlayerIDAndChapterID(ctx context.Context, arg GetChapterProgressByPlayerIDAndChapterIDParams) (GetChapterProgressByPlayerIDAndChapterIDRow, error)
	GetDailySignInByID(ctx context.Context, arg GetDailySignInByIDParams) (GetDailySignInByIDRow, error)
	GetDailySignInByPlayerID(ctx context.Context, arg GetDailySignInByPlayerIDParams) (GetDailySignInByPlayerIDRow, error)
	GetDailyTasksByPlayerID(ctx context.Context, arg GetDailyTasksByPlayerIDParams) ([]GetDailyTasksByPlayerIDRow, error)
	GetInventoryByPlayerID(ctx context.Context, id pgtype.UUID) (GetInventoryByPlayerIDRow, error)
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (GetPlayerByIDRow, error)
	GetPlayerEnergyByID(ctx context.Context, id pgtype.UUID) (GetPlayerEnergyByIDRow, error)
	GetTowerProgressByPlayerID(ctx context.Context, playerID pgtype.UUID) ([]GetTowerProgressByPlayerIDRow, error)
	GetTowerProgressByPlayerIDAndTowerID(ctx context.Context, arg GetTowerProgressByPlayerIDAndTowerIDParams) (GetTowerProgressByPlayerIDAndTowerIDRow, error)
	InitDailySignIn(ctx context.Context, arg InitDailySignInParams) (InitDailySignInRow, error)
	InsertOwnedSkins(ctx context.Context, dollar_1 []byte) ([]pgtype.UUID, error)
	MarkDailySignInDays(ctx context.Context, arg MarkDailySignInDaysParams) (MarkDailySignInDaysRow, error)
	RemoveOwnedSkins(ctx context.Context, arg RemoveOwnedSkinsParams) ([]pgtype.UUID, error)
	RemoveQuantityProp(ctx context.Context, arg RemoveQuantityPropParams) (RemoveQuantityPropRow, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (UpdatePlayerRow, error)
	UpdatePlayerEnergy(ctx context.Context, arg UpdatePlayerEnergyParams) (UpdatePlayerEnergyRow, error)
	UpsertBattleHistory(ctx context.Context, arg UpsertBattleHistoryParams) (BattleHistory, error)
	UpsertChapterProgressOnPlayer(ctx context.Context, arg UpsertChapterProgressOnPlayerParams) (UpsertChapterProgressOnPlayerRow, error)
	UpsertOwnedProps(ctx context.Context, dollar_1 []byte) ([]pgtype.UUID, error)
	UpsertProgressForDailyTask(ctx context.Context, arg UpsertProgressForDailyTaskParams) (UpsertProgressForDailyTaskRow, error)
	UpsertTowerProgressOnPlayer(ctx context.Context, arg UpsertTowerProgressOnPlayerParams) error
}

var _ Querier = (*Queries)(nil)
