// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package playersqlc

import (
	"context"
)

const dummyQuery = `-- name: dummyQuery :one
SELECT 1
`

// dummy query to make sqlc happy
// you can remove this later
func (q *Queries) dummyQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dummyQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
