version: "2"
run:
  concurrency: 4
  timeout: 5m
  tests: true # enable running linters on _test.go files

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck #~ gosimple + stylecheck merged into staticcheck
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint # detects the wrong usage of zerolog that a user forgets to dispatch zerolog.Event

    ## you may want to enable
    # - arangolint # opinionated best practices for arangodb client
    # - decorder # checks declaration order and count of types, constants, variables and functions
    # - exhaustruct # [highly recommend to enable] checks if all structure fields are initialized
    # - ginkgolinter # [if you use ginkgo/gomega] enforces standards of using ginkgo and gomega
    # - godox # detects usage of FIXME, TODO and other keywords inside comments
    # - goheader # checks is file header matches to pattern
    # - inamedparam # [great idea, but too strict, need to ignore a lot of cases by default] reports interfaces with unnamed method parameters
    # - interfacebloat # checks the number of methods inside an interface
    # - ireturn # accept interfaces, return concrete types
    # - noinlineerr # disallows inline error handling `if err := ...; err != nil {`
    # - prealloc # [premature optimization, but can be used in some cases] finds slice declarations that could potentially be preallocated
    # - tagalign # checks that struct tags are well aligned
    # - varnamelen # [great idea, but too many false positives] checks that the length of a variable's name matches its scope
    # - wrapcheck # checks that errors returned from external packages are wrapped

    # - containedctx # detects struct contained context.Context field
    # - contextcheck # [too many false positives] checks the function whether use a non-inherited context
    # - dogsled # checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    # - dupword # [useless without config] checks for duplicate words in the source code
    # - err113 # [too strict] checks the errors handling expressions
    # - errchkjson # [don't see profit + I'm against of omitting errors like in the first example https://github.com/breml/errchkjson] checks types passed to the json encoding functions. Reports unsupported types and optionally reports occasions, where the check for the returned error can be omitted
    # - forcetypeassert # [replaced by errcheck] finds forced type assertions
    # - gomodguard # [use more powerful depguard] allow and block lists linter for direct Go module dependencies
    # - gosmopolitan # reports certain i18n/l10n anti-patterns in your Go codebase
    # - grouper # analyzes expression groups
    # - importas # enforces consistent import aliases
    # - lll # [replaced by golines] reports long lines
    # - maintidx # measures the maintainability index of each function
    # - misspell # [useless] finds commonly misspelled English words in comments
    # - nlreturn # [too strict and mostly code is not more readable] checks for a new line before return and branch statements to increase code clarity
    # - paralleltest # [too many false positives] detects missing usage of t.Parallel() method in your Go test
    # - tagliatelle # checks the struct tags
    # - thelper # detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    # - wsl # [too strict and mostly code is not more readable] whitespace linter forces you to use empty lines
    # - wsl_v5 # [too strict and mostly code is not more readable] add or remove empty lines

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0
    depguard:
      rules:
        "deprecated":
          files:
            - "$all"
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead, satori's package is not maintained
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
        "non-test files":
          files:
            - "!$test"
          deny:
            - pkg: math/rand$
              desc: Use math/rand/v2 instead, see https://go.dev/blog/randv2
        "non-main files":
          files:
            - "!**/main.go"
          deny:
            - pkg: log$
              desc: Use log/slog instead, see https://go.dev/blog/slog

  exclusions:
    rules:
      - text: "should have a package comment"
        linters: [revive]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [revive]
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        linters: [revive, staticcheck]
      - text: 'package comment should be of the form ".+"'
        source: "// ?(nolint|TODO)"
        linters: [revive]

issues:
  max-issues-per-linter: 0 # no limit
  max-same-issues: 10 # limit duplicates
